imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }

    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }

    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }

    - { resource: "@SyliusApiBundle/Resources/config/app/config.yaml" }

    - { resource: "@BitBagSyliusAdyenPlugin/Resources/config/config.yaml" }

parameters:
    sylius_core.public_dir: '%kernel.project_dir%/public'
    sylius_refund.supported_gateways:
        - offline
        - adyen

sylius_api:
    enabled: true

sylius_shop:
    product_grid:
        include_all_descendants: true

bitbag_sylius_adyen:
    logger: ~
    supported_types:
        - bizum
        - applepay
        - googlepay
