parameters:
    env(MONOLOG_STREAM_PATH): '%kernel.logs_dir%/%kernel.environment%.log'

monolog:
    channels: [adyen]
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: "%env(resolve:MONOLOG_STREAM_PATH)%"
            level: debug
        doctrine:
            type: service
            channels: [ adyen ]
            id: bitbag.sylius_adyen_plugin.logging.monolog.doctrine_handler
